$schema: http://json-schema.org/draft-04/schema#
type: object
required: [editor, github-access-token, repo-storage-directory, packages]
properties:
  editor: 
    type: string
  github-access-token:
    type: string
  repo-storage-directory: 
    type: string
  packages:
      type: object
      properties:
          webviz-core-components:
            type: object
            properties:
              local: 
                type: boolean
              local_path: 
                type: string
              git_url: 
                type: string
              branch: 
                type: string
            additionalProperties: false
          webviz-subsurface-components:
            type: object
            properties:
              local: 
                type: boolean
              local_path: 
                type: string
              git_url: 
                type: string
              branch: 
                type: string
            additionalProperties: false
          webviz-subsurface:
            type: object
            properties:
              local: 
                type: boolean
              local_path: 
                type: string
              git_url: 
                type: string
              branch: 
                type: string
            additionalProperties: false
          webviz-config:
            type: object
            properties:
              local: 
                type: boolean
              local_path: 
                type: string
              git_url: 
                type: string
              branch: 
                type: string
            additionalProperties: false
